@startuml
title Структура редактора приложений


' class "Application" as Application {
    '     site : Site
    '     ' siteSelector : LoadingSelector
    '     ' pageEditor : PageEditor
    '     ' loadSite()
    '     ' loadPage()
    '     ' editPage()
    '
    '
' }
' Application *-- PageEditor
' Application *-- LoadingSelector
' Application *-- Site



class "Site" as Site {
    - _id : string
    - name : string
    - domaine : string
    - startPage_id : string
    - pages : Pages
    + updateName()
    + updateDomaine()
    + updateStartPage_id()
    + render()
}
Site *-- Pages

class "Pages" as Pages {
    - pageNames : String[]
    + constructor( site_id : string )
    - findPageNamesBySite_id( site_id : string )
    + create()
    + selectPage()
    + find( name : string )
    + delete( page : Page )
}
Pages *-- Page
class "Page" as Page {
    - _id : string
    - site_id : string
    - style_id : string
    - name : string
    - styles : Styles
    - elements : Elements
    + render()
}

Page *-- Elements
Page *-- Styles

class "Elements" as Elements {
    - elements : IElement[]
    + constructor( parent_id : string )
    - findElementsByParent_id( parent_id : string )
    + create()
    + selectElement()
    + delete( element : Element )
    + render()
}
Elements o-- Container
Elements *-- IElement
Elements o-- NamedText
Elements o-- NamedInput
Elements o-- Button

interface "IElement" as IElement {
    - _id : string
    - parent_id : string
    - style_id : string
    - name : string
    + render()
}
class "Container" as Container {
    - _id : string
    - parent_id : string
    - style_id : string
    - title : Text
    - elements : Elements
    + render()
}
Container *-- Text
Container *-- Elements
class Container implements IElement
class "NamedText" as NamedText {
    - _id : string
    - parent_id : string
    - style_id : string
    - title : Text
    - text : Text
    + render()
}
NamedText *-- Text
class NamedText implements IElement
class "NamedInput" as NamedInput {
    - _id : string
    - parent_id : string
    - style_id : string
    - title : string
    - input : Input
    + render()
}
class NamedInput implements IElement
NamedInput *-- Input
NamedInput *-- Text
class "Button" as Button {
    - _id : string
    - parent_id : string
    - style_id : string
    - title : Text    
    + render()
}
Button *-- Text
class Button implements IElement


class "Text" as Text {
    - _id : string
    - parent_id : string
    - style_id : string
    - text : string    
    + render()
}
' class "PageEditor" as PageEditor {
    '     styleEditor : StyleEditor

    '
    '
' }

' PageEditor *-- StyleEditor


' class "LoadingSelector" as LoadingSelector{

    '       selections : Selections
    '       loader : Loader
    '
    '
' }
' LoadingSelector *-- Selections


' class "Selections" as Selections{

    '     items : string[]
    '     renderEngine : RenderEngine
    '     showItems()
    '     getItems()
    '
    '
' }
' class "StyleEditor" as StyleEditor{

    '
    '
' }
' class "Page" as Page{

    '     ' render : Render
    '
    '
' }


' MyArray ..|> ICollection
' MyArray ..|> IData
' MyArray ..|> IRender
' MyArray o-- MyArray
' MyArray o-l- MyVariable
' MyArray o-- MyText
' MyArray --|> MyBaseComponent

@enduml