@startuml

(*) -->  "Проверяем является \nли объект массивом,  \nпеременной или текстом" 
  -> if "Массив" then

-->[true] "Создаем массив"

else
[false] if "Переменная" then
-->[true] "Создаем переменную"

else
-->[false] "Создаем текст"
@enduml