@startuml
title Структура базы данных


class "Entities" as Entities {
    entities: IEntity[];
    view()
}
class "Entity" as Entity {
    properties: IProperty[];
    view()
}

class "Property" as Property {
  name: string;
  view()
}




@enduml