const cssProps = {  
    display: [
      "inline",
      "block",
      "flex",
      "grid",
      "inline-block",
      "inline-flex",
      "initial",
      "inherit",
      "inline-table",
      "list-item",
      "none",
      "run-in",
      "table",
      "table-caption",
      "table-cell",
      "table-column-group",
      "table-column",
      "table-footer-group",
      "table-header-group",
      "table-row",
      "table-row-group"
    ],
    margin: ["lenght"],
    padding: ["lenght"],
    height: ["lenght"],
    width: ["lenght"],
    backgroundColor: ["color"],
    backgroundImage: ["link"],
    color: ["color"],
    borderWidth: ["lenght"],
    borderStyle: [
      "none",
      "hidden",
      "dotted",
      "dashed",
      "solid",
      "double",
      "groove",
      "ridge",
      "inset",
      "outset"
    ],
    borderColor: ["color"],
    outlineWidth: ["lenght"],
    outlineStyle: [
      "none",
      "dotted",
      "dashed",
      "solid",
      "double",
      "groove",
      "ridge",
      "inset",
      "outset",
      "inherit"
    ],
    outlineColor: ["color"],
    fontFamily: [
      "Arial",
      "Arial Black",
      "Tahoma",
      "Verdana",
      "Lucida Sans Unicode",
      "Trebuchet MS",
      "MS Sans Serif",
      "Impact",
      "Century Gothic",
      "Times New Roman",
      "Georgia",
      "Palatino Linotype",
      "MS Serif",
      "Sylfaen",
      "Garamond",
      "Century",
      "Courier New",
      "Lucida Console",
      "Consolas",
      "Сomic Sans MS",
      "Monotype Corsiva",
      "Mistral"
    ],
    fontWeight: [
      "bold",
      "bolder",
      "lighter",
      "normal",
      "100",
      "200",
      "300",
      "400",
      "500",
      "600",
      "700",
      "800",
      "900"
    ],
    fontStyle: ["normal", "italic", "oblique", "initial", "inherit"],
    fontSize: ["lenght"],
    textDecoration: [
      "blink",
      "line-through",
      "overline",
      "underline",
      "none",
      "inherit"
    ],
    textAlign: ["center", "justify", "left", "right", "start", "end"]
  
};
export {cssProps}
